id: IBF6D51DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T06:21:48+00:00'
last_modified: '2022-06-08T17:10:43.326319+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25992
  title: དོགས་སྤྱོད་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3977':
      image_group_id: I1PD36382
      title: ''
      total_pages: 392
      order: 1
      base_file: 3977.txt
    D759:
      image_group_id: I1PD36383
      title: ''
      total_pages: 410
      order: 2
      base_file: D759.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
